"""All Error & Exception definitions for Ornata."""

from __future__ import annotations


class BaseError(Exception):
    """Base error for all Ornata-specific exceptions."""
    def __init__(self, message: str) -> None:
        super().__init__(message)

class KernelError(BaseError): ...
class ComponentError(BaseError): ...
class EffectsError(BaseError): ...
class EventError(BaseError): ...
class GPUError(BaseError): ...
class LayoutError(BaseError): ...
class PluginError(KernelError): ...
class RenderingError(BaseError): ...
class StylingError(BaseError): ...
class VDOMError(BaseError): ...
class GUIError(BaseError): ...

# Kernel
class KernelInitError(KernelError): ...
class ConfigurationError(KernelError): ...
class BackendSelectionError(KernelError): ...
class PluginLoadError(PluginError): ...
class SubsystemRegistrationError(KernelError): ...
class VersionCompatibilityError(KernelError): ...
class ThemeLoadError(KernelError): ...
class EventSystemInitError(KernelError): ...
class CythonCompilationError(KernelError): ...

# Components
class ComponentLifecycleError(ComponentError): ...
class ComponentMountError(ComponentLifecycleError): ...
class ComponentUnmountError(ComponentLifecycleError): ...
class ComponentUpdateError(ComponentLifecycleError): ...
class InvalidComponentStateError(ComponentError): ...
class InvalidPropError(ComponentError): ...

# Effects
class AnimationError(EffectsError): ...
class InvalidKeyframeError(AnimationError): ...
class AnimationNotFoundError(AnimationError): ...
class AnimationStateError(AnimationError): ...
class EasingFunctionError(AnimationError): ...
class ParticleError(EffectsError): ...
class InvalidParticleConfigError(ParticleError): ...
class ParticleSystemNotFoundError(ParticleError): ...

# GPU
class GPUBackendNotAvailableError(GPUError): ...
class GPUShaderCompilationError(GPUError): ...
class GPUDeviceError(GPUError): ...
class GPUMemoryError(GPUError): ...
class GPUPipelineError(GPUError): ...
class GPUContextLostError(GPUError): ...
class GPUFeatureUnsupportedError(GPUError): ...
class GPUBufferError(GPUError): ...
class GPUBufferCreationError(GPUBufferError): ...
class GPUBufferUpdateError(GPUBufferError): ...
class GPUBufferBindingError(GPUBufferError): ...
class GPUBufferAlignmentError(GPUBufferError): ...

# Rendering
class UnsupportedRendererError(RenderingError): ...
class CompositionError(RenderingError): ...
class PipelineError(RenderingError): ...
class FrameSubmissionError(RenderingError): ...

# Styling
class ValidationError(StylingError): ...
class StyleResolutionError(StylingError): ...
class InvalidStyleValueError(StylingError): ...
class StyleNotFoundError(StylingError): ...
class ThemeOverrideError(StylingError): ...
class ThemeTokenNotFoundError(StylingError): ...

# VDOM
class ComponentNotFoundError(VDOMError): ...
class InvalidVDOMOperationError(VDOMError): ...
class VDOMReconciliationError(VDOMError): ...
class DiffingError(VDOMError): ...
class InvalidTreeStructureError(DiffingError): ...
class PatchApplicationError(DiffingError): ...
class MissingKeyError(DiffingError): ...
class KeyCollisionError(DiffingError): ...

# Layout
class LayoutCalculationError(LayoutError): ...
class InvalidLayoutConstraintsError(LayoutError): ...
class LayoutOverflowError(LayoutError): ...
class LayoutUnderflowError(LayoutError): ...

# GUI
class WindowCreationError(GUIError): ...
class ContextCreationError(GUIError): ...
class SurfaceCreationError(GUIError): ...
class GUIEventLoopError(GUIError): ...

# Events
class EventPropagationError(EventError): ...
class InvalidEventTypeError(EventError): ...
class EventHandlerError(EventError): ...
class EventReplayError(EventError): ...
class EventSubscriptionError(EventError): ...
class EventQueueOverflowError(EventError): ...

__all__ = [
    "BaseError",
    "KernelError",
    "ComponentError",
    "EffectsError",
    "EventError",
    "GPUError",
    "LayoutError",
    "PluginError",
    "RenderingError",
    "StylingError",
    "VDOMError",
    "GUIError",
    "KernelInitError",
    "ConfigurationError",
    "BackendSelectionError",
    "PluginLoadError",
    "SubsystemRegistrationError",
    "VersionCompatibilityError",
    "ThemeLoadError",
    "EventSystemInitError",
    "CythonCompilationError",
    "ComponentLifecycleError",
    "ComponentMountError",
    "ComponentUnmountError",
    "ComponentUpdateError",
    "InvalidComponentStateError",
    "InvalidPropError",
    "AnimationError",
    "InvalidKeyframeError",
    "AnimationNotFoundError",
    "AnimationStateError",
    "EasingFunctionError",
    "ParticleError",
    "InvalidParticleConfigError",
    "ParticleSystemNotFoundError",
    "GPUBackendNotAvailableError",
    "GPUShaderCompilationError",
    "GPUDeviceError",
    "GPUMemoryError",
    "GPUPipelineError",
    "GPUContextLostError",
    "GPUFeatureUnsupportedError",
    "GPUBufferError",
    "GPUBufferCreationError",
    "GPUBufferUpdateError",
    "GPUBufferBindingError",
    "GPUBufferAlignmentError",
    "UnsupportedRendererError",
    "CompositionError",
    "PipelineError",
    "FrameSubmissionError",
    "ValidationError",
    "StyleResolutionError",
    "InvalidStyleValueError",
    "StyleNotFoundError",
    "ThemeOverrideError",
    "ThemeTokenNotFoundError",
    "ComponentNotFoundError",
    "InvalidVDOMOperationError",
    "VDOMReconciliationError",
    "DiffingError",
    "InvalidTreeStructureError",
    "PatchApplicationError",
    "MissingKeyError",
    "KeyCollisionError",
    "LayoutCalculationError",
    "InvalidLayoutConstraintsError",
    "LayoutOverflowError",
    "LayoutUnderflowError",
    "WindowCreationError",
    "ContextCreationError",
    "SurfaceCreationError",
    "GUIEventLoopError",
    "EventPropagationError",
    "InvalidEventTypeError",
    "EventHandlerError",
    "EventReplayError",
    "EventSubscriptionError",
    "EventQueueOverflowError",
]