"""Auto-generated lazy exports for the definitions subsystem."""

from __future__ import annotations

from importlib import import_module

from ornata.api._warnings import setup_internal_warnings

setup_internal_warnings()

_EXPORT_TARGETS: dict[str, str] = {
    "constants": "ornata.definitions:constants",
    "dataclasses": "ornata.definitions:dataclasses",
    "enums": "ornata.definitions:enums",
    "errors": "ornata.definitions:errors",
    "flags": "ornata.definitions:flags",
    "protocols": "ornata.definitions:protocols",
    "type_alias": "ornata.definitions:type_alias",
    "unicode_assets": "ornata.definitions:unicode_assets",
    "BOX_LIGHT_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_LIGHT_HORIZONTAL",
    "BOX_LIGHT_VERTICAL": "ornata.definitions.unicode_assets:BOX_LIGHT_VERTICAL",
    "BOX_LIGHT_DOWN_RIGHT": "ornata.definitions.unicode_assets:BOX_LIGHT_DOWN_RIGHT",
    "BOX_LIGHT_DOWN_LEFT": "ornata.definitions.unicode_assets:BOX_LIGHT_DOWN_LEFT",
    "BOX_LIGHT_UP_RIGHT": "ornata.definitions.unicode_assets:BOX_LIGHT_UP_RIGHT",
    "BOX_LIGHT_UP_LEFT": "ornata.definitions.unicode_assets:BOX_LIGHT_UP_LEFT",
    "BOX_LIGHT_VERTICAL_RIGHT": "ornata.definitions.unicode_assets:BOX_LIGHT_VERTICAL_RIGHT",
    "BOX_LIGHT_VERTICAL_LEFT": "ornata.definitions.unicode_assets:BOX_LIGHT_VERTICAL_LEFT",
    "BOX_LIGHT_DOWN_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_LIGHT_DOWN_HORIZONTAL",
    "BOX_LIGHT_UP_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_LIGHT_UP_HORIZONTAL",
    "BOX_LIGHT_CROSS": "ornata.definitions.unicode_assets:BOX_LIGHT_CROSS",
    "BOX_HEAVY_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_HEAVY_HORIZONTAL",
    "BOX_HEAVY_VERTICAL": "ornata.definitions.unicode_assets:BOX_HEAVY_VERTICAL",
    "BOX_HEAVY_DOWN_RIGHT": "ornata.definitions.unicode_assets:BOX_HEAVY_DOWN_RIGHT",
    "BOX_HEAVY_DOWN_LEFT": "ornata.definitions.unicode_assets:BOX_HEAVY_DOWN_LEFT",
    "BOX_HEAVY_UP_RIGHT": "ornata.definitions.unicode_assets:BOX_HEAVY_UP_RIGHT",
    "BOX_HEAVY_UP_LEFT": "ornata.definitions.unicode_assets:BOX_HEAVY_UP_LEFT",
    "BOX_HEAVY_VERTICAL_RIGHT": "ornata.definitions.unicode_assets:BOX_HEAVY_VERTICAL_RIGHT",
    "BOX_HEAVY_VERTICAL_LEFT": "ornata.definitions.unicode_assets:BOX_HEAVY_VERTICAL_LEFT",
    "BOX_HEAVY_DOWN_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_HEAVY_DOWN_HORIZONTAL",
    "BOX_HEAVY_UP_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_HEAVY_UP_HORIZONTAL",
    "BOX_HEAVY_CROSS": "ornata.definitions.unicode_assets:BOX_HEAVY_CROSS",
    "BOX_DOUBLE_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_DOUBLE_HORIZONTAL",
    "BOX_DOUBLE_VERTICAL": "ornata.definitions.unicode_assets:BOX_DOUBLE_VERTICAL",
    "BOX_DOUBLE_DOWN_RIGHT": "ornata.definitions.unicode_assets:BOX_DOUBLE_DOWN_RIGHT",
    "BOX_DOUBLE_DOWN_LEFT": "ornata.definitions.unicode_assets:BOX_DOUBLE_DOWN_LEFT",
    "BOX_DOUBLE_UP_RIGHT": "ornata.definitions.unicode_assets:BOX_DOUBLE_UP_RIGHT",
    "BOX_DOUBLE_UP_LEFT": "ornata.definitions.unicode_assets:BOX_DOUBLE_UP_LEFT",
    "BOX_DOUBLE_VERTICAL_RIGHT": "ornata.definitions.unicode_assets:BOX_DOUBLE_VERTICAL_RIGHT",
    "BOX_DOUBLE_VERTICAL_LEFT": "ornata.definitions.unicode_assets:BOX_DOUBLE_VERTICAL_LEFT",
    "BOX_DOUBLE_DOWN_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_DOUBLE_DOWN_HORIZONTAL",
    "BOX_DOUBLE_UP_HORIZONTAL": "ornata.definitions.unicode_assets:BOX_DOUBLE_UP_HORIZONTAL",
    "BOX_DOUBLE_CROSS": "ornata.definitions.unicode_assets:BOX_DOUBLE_CROSS",
    "BOX_ARC_DOWN_RIGHT": "ornata.definitions.unicode_assets:BOX_ARC_DOWN_RIGHT",
    "BOX_ARC_DOWN_LEFT": "ornata.definitions.unicode_assets:BOX_ARC_DOWN_LEFT",
    "BOX_ARC_UP_LEFT": "ornata.definitions.unicode_assets:BOX_ARC_UP_LEFT",
    "BOX_ARC_UP_RIGHT": "ornata.definitions.unicode_assets:BOX_ARC_UP_RIGHT",
    "BOX_LIGHT_TRIPLE_DASH_HZ": "ornata.definitions.unicode_assets:BOX_LIGHT_TRIPLE_DASH_HZ",
    "BOX_HEAVY_TRIPLE_DASH_HZ": "ornata.definitions.unicode_assets:BOX_HEAVY_TRIPLE_DASH_HZ",
    "BOX_LIGHT_TRIPLE_DASH_VT": "ornata.definitions.unicode_assets:BOX_LIGHT_TRIPLE_DASH_VT",
    "BOX_HEAVY_TRIPLE_DASH_VT": "ornata.definitions.unicode_assets:BOX_HEAVY_TRIPLE_DASH_VT",
    "BOX_LIGHT_QUAD_DASH_HZ": "ornata.definitions.unicode_assets:BOX_LIGHT_QUAD_DASH_HZ",
    "BOX_HEAVY_QUAD_DASH_HZ": "ornata.definitions.unicode_assets:BOX_HEAVY_QUAD_DASH_HZ",
    "BOX_LIGHT_QUAD_DASH_VT": "ornata.definitions.unicode_assets:BOX_LIGHT_QUAD_DASH_VT",
    "BOX_HEAVY_QUAD_DASH_VT": "ornata.definitions.unicode_assets:BOX_HEAVY_QUAD_DASH_VT",
    "BOX_LIGHT_DOUBLE_DASH_HZ": "ornata.definitions.unicode_assets:BOX_LIGHT_DOUBLE_DASH_HZ",
    "BOX_HEAVY_DOUBLE_DASH_HZ": "ornata.definitions.unicode_assets:BOX_HEAVY_DOUBLE_DASH_HZ",
    "BOX_LIGHT_DOUBLE_DASH_VT": "ornata.definitions.unicode_assets:BOX_LIGHT_DOUBLE_DASH_VT",
    "BOX_HEAVY_DOUBLE_DASH_VT": "ornata.definitions.unicode_assets:BOX_HEAVY_DOUBLE_DASH_VT",
    "BOX_DOWN_LIGHT_RIGHT_HEAVY": "ornata.definitions.unicode_assets:BOX_DOWN_LIGHT_RIGHT_HEAVY",
    "BOX_DOWN_HEAVY_RIGHT_LIGHT": "ornata.definitions.unicode_assets:BOX_DOWN_HEAVY_RIGHT_LIGHT",
    "BOX_DOWN_LIGHT_LEFT_HEAVY": "ornata.definitions.unicode_assets:BOX_DOWN_LIGHT_LEFT_HEAVY",
    "BOX_DOWN_HEAVY_LEFT_LIGHT": "ornata.definitions.unicode_assets:BOX_DOWN_HEAVY_LEFT_LIGHT",
    "BOX_UP_LIGHT_RIGHT_HEAVY": "ornata.definitions.unicode_assets:BOX_UP_LIGHT_RIGHT_HEAVY",
    "BOX_UP_HEAVY_RIGHT_LIGHT": "ornata.definitions.unicode_assets:BOX_UP_HEAVY_RIGHT_LIGHT",
    "BOX_UP_LIGHT_LEFT_HEAVY": "ornata.definitions.unicode_assets:BOX_UP_LIGHT_LEFT_HEAVY",
    "BOX_UP_HEAVY_LEFT_LIGHT": "ornata.definitions.unicode_assets:BOX_UP_HEAVY_LEFT_LIGHT",
    "BOX_DIAGONAL_UP_RIGHT": "ornata.definitions.unicode_assets:BOX_DIAGONAL_UP_RIGHT",
    "BOX_DIAGONAL_UP_LEFT": "ornata.definitions.unicode_assets:BOX_DIAGONAL_UP_LEFT",
    "BOX_DIAGONAL_CROSS": "ornata.definitions.unicode_assets:BOX_DIAGONAL_CROSS",
    "BORDER_STYLES": "ornata.definitions.unicode_assets:BORDER_STYLES",
    "BLOCK_SHADE_LIGHT": "ornata.definitions.unicode_assets:BLOCK_SHADE_LIGHT",
    "BLOCK_SHADE_MEDIUM": "ornata.definitions.unicode_assets:BLOCK_SHADE_MEDIUM",
    "BLOCK_SHADE_DARK": "ornata.definitions.unicode_assets:BLOCK_SHADE_DARK",
    "BLOCK_LOWER_1_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_1_8",
    "BLOCK_LOWER_2_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_2_8",
    "BLOCK_LOWER_3_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_3_8",
    "BLOCK_LOWER_4_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_4_8",
    "BLOCK_LOWER_5_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_5_8",
    "BLOCK_LOWER_6_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_6_8",
    "BLOCK_LOWER_7_8": "ornata.definitions.unicode_assets:BLOCK_LOWER_7_8",
    "BLOCK_UPPER_HALF": "ornata.definitions.unicode_assets:BLOCK_UPPER_HALF",
    "BLOCK_LEFT_1_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_1_8",
    "BLOCK_LEFT_2_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_2_8",
    "BLOCK_LEFT_3_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_3_8",
    "BLOCK_LEFT_4_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_4_8",
    "BLOCK_LEFT_5_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_5_8",
    "BLOCK_LEFT_6_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_6_8",
    "BLOCK_LEFT_7_8": "ornata.definitions.unicode_assets:BLOCK_LEFT_7_8",
    "BLOCK_FULL": "ornata.definitions.unicode_assets:BLOCK_FULL",
    "BLOCK_QUAD_LOWER_LEFT": "ornata.definitions.unicode_assets:BLOCK_QUAD_LOWER_LEFT",
    "BLOCK_QUAD_LOWER_RIGHT": "ornata.definitions.unicode_assets:BLOCK_QUAD_LOWER_RIGHT",
    "BLOCK_QUAD_UPPER_LEFT": "ornata.definitions.unicode_assets:BLOCK_QUAD_UPPER_LEFT",
    "BLOCK_QUAD_UPPER_RIGHT": "ornata.definitions.unicode_assets:BLOCK_QUAD_UPPER_RIGHT",
    "BAR_LEVELS_VERTICAL": "ornata.definitions.unicode_assets:BAR_LEVELS_VERTICAL",
    "BAR_LEVELS_HORIZONTAL": "ornata.definitions.unicode_assets:BAR_LEVELS_HORIZONTAL",
    "SHADES": "ornata.definitions.unicode_assets:SHADES",
    "ICON_CHECK": "ornata.definitions.unicode_assets:ICON_CHECK",
    "ICON_CROSS": "ornata.definitions.unicode_assets:ICON_CROSS",
    "ICON_RADIO_ON": "ornata.definitions.unicode_assets:ICON_RADIO_ON",
    "ICON_RADIO_OFF": "ornata.definitions.unicode_assets:ICON_RADIO_OFF",
    "ICON_CHECKBOX_ON": "ornata.definitions.unicode_assets:ICON_CHECKBOX_ON",
    "ICON_CHECKBOX_OFF": "ornata.definitions.unicode_assets:ICON_CHECKBOX_OFF",
    "ICON_STAR_FILLED": "ornata.definitions.unicode_assets:ICON_STAR_FILLED",
    "ICON_STAR_EMPTY": "ornata.definitions.unicode_assets:ICON_STAR_EMPTY",
    "ICON_HEART_FILLED": "ornata.definitions.unicode_assets:ICON_HEART_FILLED",
    "ICON_HEART_EMPTY": "ornata.definitions.unicode_assets:ICON_HEART_EMPTY",
    "ICON_WARNING": "ornata.definitions.unicode_assets:ICON_WARNING",
    "ICON_ERROR": "ornata.definitions.unicode_assets:ICON_ERROR",
    "ICON_INFO": "ornata.definitions.unicode_assets:ICON_INFO",
    "ICON_SETTINGS": "ornata.definitions.unicode_assets:ICON_SETTINGS",
    "ICON_LOCK": "ornata.definitions.unicode_assets:ICON_LOCK",
    "ICON_UNLOCK": "ornata.definitions.unicode_assets:ICON_UNLOCK",
    "ICON_MAIL": "ornata.definitions.unicode_assets:ICON_MAIL",
    "ICON_EDIT": "ornata.definitions.unicode_assets:ICON_EDIT",
    "ICON_DELETE": "ornata.definitions.unicode_assets:ICON_DELETE",
    "ICON_SEARCH": "ornata.definitions.unicode_assets:ICON_SEARCH",
    "ARROW_LEFT": "ornata.definitions.unicode_assets:ARROW_LEFT",
    "ARROW_UP": "ornata.definitions.unicode_assets:ARROW_UP",
    "ARROW_RIGHT": "ornata.definitions.unicode_assets:ARROW_RIGHT",
    "ARROW_DOWN": "ornata.definitions.unicode_assets:ARROW_DOWN",
    "ARROW_LEFT_RIGHT": "ornata.definitions.unicode_assets:ARROW_LEFT_RIGHT",
    "ARROW_UP_DOWN": "ornata.definitions.unicode_assets:ARROW_UP_DOWN",
    "TRIANGLE_UP": "ornata.definitions.unicode_assets:TRIANGLE_UP",
    "TRIANGLE_DOWN": "ornata.definitions.unicode_assets:TRIANGLE_DOWN",
    "TRIANGLE_LEFT": "ornata.definitions.unicode_assets:TRIANGLE_LEFT",
    "TRIANGLE_RIGHT": "ornata.definitions.unicode_assets:TRIANGLE_RIGHT",
    "TRIANGLE_UP_SMALL": "ornata.definitions.unicode_assets:TRIANGLE_UP_SMALL",
    "TRIANGLE_DOWN_SMALL": "ornata.definitions.unicode_assets:TRIANGLE_DOWN_SMALL",
    "TRIANGLE_LEFT_SMALL": "ornata.definitions.unicode_assets:TRIANGLE_LEFT_SMALL",
    "TRIANGLE_RIGHT_SMALL": "ornata.definitions.unicode_assets:TRIANGLE_RIGHT_SMALL",
    "LIST_BOX_DRAWING": "ornata.definitions.unicode_assets:LIST_BOX_DRAWING",
    "LIST_BLOCK_ELEMENTS": "ornata.definitions.unicode_assets:LIST_BLOCK_ELEMENTS",
    "LIST_GEOMETRIC_SHAPES": "ornata.definitions.unicode_assets:LIST_GEOMETRIC_SHAPES",
    "LIST_ARROWS": "ornata.definitions.unicode_assets:LIST_ARROWS",
    "LIST_MISC_SYMBOLS": "ornata.definitions.unicode_assets:LIST_MISC_SYMBOLS",
    "LIST_DINGBATS": "ornata.definitions.unicode_assets:LIST_DINGBATS",
    "LIST_BRAILLE": "ornata.definitions.unicode_assets:LIST_BRAILLE",
    "LIST_MATH_OPERATORS": "ornata.definitions.unicode_assets:LIST_MATH_OPERATORS",
    "LIST_ASCII_PRINTABLE": "ornata.definitions.unicode_assets:LIST_ASCII_PRINTABLE",
    "ROUTE_FILTER": "ornata.definitions.constants:ROUTE_FILTER",
    "ROUTE_HANDLER": "ornata.definitions.constants:ROUTE_HANDLER",
    "ROUTE_GLOBAL": "ornata.definitions.constants:ROUTE_GLOBAL",
    "ROUTE_SUBSYSTEM": "ornata.definitions.constants:ROUTE_SUBSYSTEM",
    "ROUTE_ALL": "ornata.definitions.constants:ROUTE_ALL",
    "ZERO_TIME": "ornata.definitions.constants:ZERO_TIME",
    "DEFAULT_COMPONENT_WIDTH": "ornata.definitions.constants:DEFAULT_COMPONENT_WIDTH",
    "DEFAULT_COMPONENT_HEIGHT": "ornata.definitions.constants:DEFAULT_COMPONENT_HEIGHT",
    "MIN_PATCH_OPTIMIZATION": "ornata.definitions.constants:MIN_PATCH_OPTIMIZATION",
    "SCHED_LOCAL": "ornata.definitions.constants:SCHED_LOCAL",
    "RECONCILER_LOCAL": "ornata.definitions.constants:RECONCILER_LOCAL",
    "GLOBAL_REGISTRY": "ornata.definitions.constants:GLOBAL_REGISTRY",
    "VALID_STYLING_PROPERTIES": "ornata.definitions.constants:VALID_STYLING_PROPERTIES",
    "VALUE_PATTERNS": "ornata.definitions.constants:VALUE_PATTERNS",
    "SPACING_SCALE": "ornata.definitions.constants:SPACING_SCALE",
    "TYPOGRAPHY_SCALE": "ornata.definitions.constants:TYPOGRAPHY_SCALE",
    "PROPERTIES": "ornata.definitions.constants:PROPERTIES",
    "UNICODE_BOX": "ornata.definitions.constants:UNICODE_BOX",
    "UNICODE_DOUBLE_BOX": "ornata.definitions.constants:UNICODE_DOUBLE_BOX",
    "UNICODE_ROUNDED_BOX": "ornata.definitions.constants:UNICODE_ROUNDED_BOX",
    "UNICODE_THICK_BOX": "ornata.definitions.constants:UNICODE_THICK_BOX",
    "SUFFIX_TO_UNIT": "ornata.definitions.constants:SUFFIX_TO_UNIT",
    "COMPONENT_CACHE_LIMIT": "ornata.definitions.constants:COMPONENT_CACHE_LIMIT",
    "EFFECTS_CACHE_LIMIT": "ornata.definitions.constants:EFFECTS_CACHE_LIMIT",
    "EVENTS_CACHE_LIMIT": "ornata.definitions.constants:EVENTS_CACHE_LIMIT",
    "GPU_CACHE_LIMIT": "ornata.definitions.constants:GPU_CACHE_LIMIT",
    "LAYOUT_CACHE_LIMIT": "ornata.definitions.constants:LAYOUT_CACHE_LIMIT",
    "RENDERING_CACHE_LIMIT": "ornata.definitions.constants:RENDERING_CACHE_LIMIT",
    "STYLING_CACHE_LIMIT": "ornata.definitions.constants:STYLING_CACHE_LIMIT",
    "VDOM_CACHE_LIMIT": "ornata.definitions.constants:VDOM_CACHE_LIMIT",
    "LAST_COMPONENT_ERRORS": "ornata.definitions.constants:LAST_COMPONENT_ERRORS",
    "LAST_EFFECTS_ERRORS": "ornata.definitions.constants:LAST_EFFECTS_ERRORS",
    "LAST_EVENTS_ERRORS": "ornata.definitions.constants:LAST_EVENTS_ERRORS",
    "LAST_GPU_ERRORS": "ornata.definitions.constants:LAST_GPU_ERRORS",
    "LAST_LAYOUT_ERRORS": "ornata.definitions.constants:LAST_LAYOUT_ERRORS",
    "LAST_RENDERING_ERRORS": "ornata.definitions.constants:LAST_RENDERING_ERRORS",
    "LAST_STYLING_ERRORS": "ornata.definitions.constants:LAST_STYLING_ERRORS",
    "LAST_VDOM_ERRORS": "ornata.definitions.constants:LAST_VDOM_ERRORS",
    "LAST_COMPONENT_WARNINGS": "ornata.definitions.constants:LAST_COMPONENT_WARNINGS",
    "LAST_EFFECTS_WARNINGS": "ornata.definitions.constants:LAST_EFFECTS_WARNINGS",
    "LAST_EVENTS_WARNINGS": "ornata.definitions.constants:LAST_EVENTS_WARNINGS",
    "LAST_GPU_WARNINGS": "ornata.definitions.constants:LAST_GPU_WARNINGS",
    "LAST_LAYOUT_WARNINGS": "ornata.definitions.constants:LAST_LAYOUT_WARNINGS",
    "LAST_RENDERING_WARNINGS": "ornata.definitions.constants:LAST_RENDERING_WARNINGS",
    "LAST_STYLING_WARNINGS": "ornata.definitions.constants:LAST_STYLING_WARNINGS",
    "LAST_VDOM_WARNINGS": "ornata.definitions.constants:LAST_VDOM_WARNINGS",
    "ANSI_CACHE_LIMIT": "ornata.definitions.constants:ANSI_CACHE_LIMIT",
    "BACKGROUND_CACHE_LIMIT": "ornata.definitions.constants:BACKGROUND_CACHE_LIMIT",
    "RGB_CACHE_LIMIT": "ornata.definitions.constants:RGB_CACHE_LIMIT",
    "GRADIENT_CACHE_LIMIT": "ornata.definitions.constants:GRADIENT_CACHE_LIMIT",
    "COLOR_CACHE": "ornata.definitions.constants:COLOR_CACHE",
    "TRANSFORMS": "ornata.definitions.constants:TRANSFORMS",
    "VAR_PATTERN": "ornata.definitions.constants:VAR_PATTERN",
    "THEME_TOKEN_PATTERN": "ornata.definitions.constants:THEME_TOKEN_PATTERN",
    "ANSI_INDEX_PATTERN": "ornata.definitions.constants:ANSI_INDEX_PATTERN",
    "HEX_PATTERN": "ornata.definitions.constants:HEX_PATTERN",
    "RGB_PATTERN": "ornata.definitions.constants:RGB_PATTERN",
    "RGBA_PATTERN": "ornata.definitions.constants:RGBA_PATTERN",
    "HSL_PATTERN": "ornata.definitions.constants:HSL_PATTERN",
    "HSLA_PATTERN": "ornata.definitions.constants:HSLA_PATTERN",
    "RGB_COMMA_PATTERN": "ornata.definitions.constants:RGB_COMMA_PATTERN",
    "NAMED_COLORS": "ornata.definitions.constants:NAMED_COLORS",
    "NAMED_HEX": "ornata.definitions.constants:NAMED_HEX",
    "ANSI_4BIT_RGB": "ornata.definitions.constants:ANSI_4BIT_RGB",
    "BACKGROUND_COLORS": "ornata.definitions.constants:BACKGROUND_COLORS",
    "EFFECTS": "ornata.definitions.constants:EFFECTS",
    "ESC": "ornata.definitions.constants:ESC",
    "CSI": "ornata.definitions.constants:CSI",
    "OSC": "ornata.definitions.constants:OSC",
    "BEL": "ornata.definitions.constants:BEL",
    "BS": "ornata.definitions.constants:BS",
    "CR": "ornata.definitions.constants:CR",
    "LF": "ornata.definitions.constants:LF",
    "CRLF": "ornata.definitions.constants:CRLF",
    "SGR_RESET_ALL": "ornata.definitions.constants:SGR_RESET_ALL",
    "SGR_BOLD": "ornata.definitions.constants:SGR_BOLD",
    "SGR_DIM": "ornata.definitions.constants:SGR_DIM",
    "SGR_ITALIC": "ornata.definitions.constants:SGR_ITALIC",
    "SGR_UNDERLINE": "ornata.definitions.constants:SGR_UNDERLINE",
    "SGR_BLINK": "ornata.definitions.constants:SGR_BLINK",
    "SGR_RAPID_BLINK": "ornata.definitions.constants:SGR_RAPID_BLINK",
    "SGR_REVERSE": "ornata.definitions.constants:SGR_REVERSE",
    "SGR_HIDDEN": "ornata.definitions.constants:SGR_HIDDEN",
    "SGR_STRIKETHROUGH": "ornata.definitions.constants:SGR_STRIKETHROUGH",
    "SGR_RESET_BOLD_DIM": "ornata.definitions.constants:SGR_RESET_BOLD_DIM",
    "SGR_RESET_ITALIC": "ornata.definitions.constants:SGR_RESET_ITALIC",
    "SGR_RESET_UNDERLINE": "ornata.definitions.constants:SGR_RESET_UNDERLINE",
    "SGR_RESET_BLINK": "ornata.definitions.constants:SGR_RESET_BLINK",
    "SGR_RESET_REVERSE": "ornata.definitions.constants:SGR_RESET_REVERSE",
    "SGR_RESET_HIDDEN": "ornata.definitions.constants:SGR_RESET_HIDDEN",
    "SGR_RESET_STRIKETHROUGH": "ornata.definitions.constants:SGR_RESET_STRIKETHROUGH",
    "SGR_FONT_PRIMARY": "ornata.definitions.constants:SGR_FONT_PRIMARY",
    "SGR_FONT_ALTERNATE_1": "ornata.definitions.constants:SGR_FONT_ALTERNATE_1",
    "SGR_FONT_ALTERNATE_2": "ornata.definitions.constants:SGR_FONT_ALTERNATE_2",
    "SGR_FONT_ALTERNATE_3": "ornata.definitions.constants:SGR_FONT_ALTERNATE_3",
    "SGR_FONT_ALTERNATE_4": "ornata.definitions.constants:SGR_FONT_ALTERNATE_4",
    "SGR_FONT_ALTERNATE_5": "ornata.definitions.constants:SGR_FONT_ALTERNATE_5",
    "SGR_FONT_ALTERNATE_6": "ornata.definitions.constants:SGR_FONT_ALTERNATE_6",
    "SGR_FONT_ALTERNATE_7": "ornata.definitions.constants:SGR_FONT_ALTERNATE_7",
    "SGR_FONT_ALTERNATE_8": "ornata.definitions.constants:SGR_FONT_ALTERNATE_8",
    "SGR_FONT_ALTERNATE_9": "ornata.definitions.constants:SGR_FONT_ALTERNATE_9",
    "SGR_FRAKTUR": "ornata.definitions.constants:SGR_FRAKTUR",
    "SGR_UNDERLINE_DOUBLE": "ornata.definitions.constants:SGR_UNDERLINE_DOUBLE",
    "SGR_IDEOGRAM_UNDERLINE": "ornata.definitions.constants:SGR_IDEOGRAM_UNDERLINE",
    "SGR_IDEOGRAM_DOUBLE_UNDERLINE": "ornata.definitions.constants:SGR_IDEOGRAM_DOUBLE_UNDERLINE",
    "SGR_IDEOGRAM_OVERLINE": "ornata.definitions.constants:SGR_IDEOGRAM_OVERLINE",
    "SGR_IDEOGRAM_DOUBLE_OVERLINE": "ornata.definitions.constants:SGR_IDEOGRAM_DOUBLE_OVERLINE",
    "SGR_IDEOGRAM_STRESS": "ornata.definitions.constants:SGR_IDEOGRAM_STRESS",
    "SGR_SUPERSCRIPT": "ornata.definitions.constants:SGR_SUPERSCRIPT",
    "SGR_SUBSCRIPT": "ornata.definitions.constants:SGR_SUBSCRIPT",
    "RESET_ALL": "ornata.definitions.constants:RESET_ALL",
    "RESET_FOREGROUND": "ornata.definitions.constants:RESET_FOREGROUND",
    "RESET_BACKGROUND": "ornata.definitions.constants:RESET_BACKGROUND",
    "FG_BLACK": "ornata.definitions.constants:FG_BLACK",
    "FG_RED": "ornata.definitions.constants:FG_RED",
    "FG_GREEN": "ornata.definitions.constants:FG_GREEN",
    "FG_YELLOW": "ornata.definitions.constants:FG_YELLOW",
    "FG_BLUE": "ornata.definitions.constants:FG_BLUE",
    "FG_MAGENTA": "ornata.definitions.constants:FG_MAGENTA",
    "FG_CYAN": "ornata.definitions.constants:FG_CYAN",
    "FG_WHITE": "ornata.definitions.constants:FG_WHITE",
    "BG_BLACK": "ornata.definitions.constants:BG_BLACK",
    "BG_RED": "ornata.definitions.constants:BG_RED",
    "BG_GREEN": "ornata.definitions.constants:BG_GREEN",
    "BG_YELLOW": "ornata.definitions.constants:BG_YELLOW",
    "BG_BLUE": "ornata.definitions.constants:BG_BLUE",
    "BG_MAGENTA": "ornata.definitions.constants:BG_MAGENTA",
    "BG_CYAN": "ornata.definitions.constants:BG_CYAN",
    "BG_WHITE": "ornata.definitions.constants:BG_WHITE",
    "FG_BRIGHT_BLACK": "ornata.definitions.constants:FG_BRIGHT_BLACK",
    "FG_BRIGHT_RED": "ornata.definitions.constants:FG_BRIGHT_RED",
    "FG_BRIGHT_GREEN": "ornata.definitions.constants:FG_BRIGHT_GREEN",
    "FG_BRIGHT_YELLOW": "ornata.definitions.constants:FG_BRIGHT_YELLOW",
    "FG_BRIGHT_BLUE": "ornata.definitions.constants:FG_BRIGHT_BLUE",
    "FG_BRIGHT_MAGENTA": "ornata.definitions.constants:FG_BRIGHT_MAGENTA",
    "FG_BRIGHT_CYAN": "ornata.definitions.constants:FG_BRIGHT_CYAN",
    "FG_BRIGHT_WHITE": "ornata.definitions.constants:FG_BRIGHT_WHITE",
    "BG_BRIGHT_BLACK": "ornata.definitions.constants:BG_BRIGHT_BLACK",
    "BG_BRIGHT_RED": "ornata.definitions.constants:BG_BRIGHT_RED",
    "BG_BRIGHT_GREEN": "ornata.definitions.constants:BG_BRIGHT_GREEN",
    "BG_BRIGHT_YELLOW": "ornata.definitions.constants:BG_BRIGHT_YELLOW",
    "BG_BRIGHT_BLUE": "ornata.definitions.constants:BG_BRIGHT_BLUE",
    "BG_BRIGHT_MAGENTA": "ornata.definitions.constants:BG_BRIGHT_MAGENTA",
    "BG_BRIGHT_CYAN": "ornata.definitions.constants:BG_BRIGHT_CYAN",
    "BG_BRIGHT_WHITE": "ornata.definitions.constants:BG_BRIGHT_WHITE",
    "ANSI_16_COLORS": "ornata.definitions.constants:ANSI_16_COLORS",
    "ANSI_16_FOREGROUND": "ornata.definitions.constants:ANSI_16_FOREGROUND",
    "ANSI_16_BACKGROUND": "ornata.definitions.constants:ANSI_16_BACKGROUND",
    "COLOR_BLACK": "ornata.definitions.constants:COLOR_BLACK",
    "COLOR_WHITE": "ornata.definitions.constants:COLOR_WHITE",
    "COLOR_RED": "ornata.definitions.constants:COLOR_RED",
    "COLOR_GREEN": "ornata.definitions.constants:COLOR_GREEN",
    "COLOR_BLUE": "ornata.definitions.constants:COLOR_BLUE",
    "COLOR_YELLOW": "ornata.definitions.constants:COLOR_YELLOW",
    "COLOR_MAGENTA": "ornata.definitions.constants:COLOR_MAGENTA",
    "COLOR_CYAN": "ornata.definitions.constants:COLOR_CYAN",
    "COLOR_GRAY": "ornata.definitions.constants:COLOR_GRAY",
    "CURSOR_UP": "ornata.definitions.constants:CURSOR_UP",
    "CURSOR_DOWN": "ornata.definitions.constants:CURSOR_DOWN",
    "CURSOR_RIGHT": "ornata.definitions.constants:CURSOR_RIGHT",
    "CURSOR_LEFT": "ornata.definitions.constants:CURSOR_LEFT",
    "CURSOR_HOME": "ornata.definitions.constants:CURSOR_HOME",
    "CURSOR_SAVE": "ornata.definitions.constants:CURSOR_SAVE",
    "CURSOR_RESTORE": "ornata.definitions.constants:CURSOR_RESTORE",
    "CURSOR_HIDE": "ornata.definitions.constants:CURSOR_HIDE",
    "CURSOR_SHOW": "ornata.definitions.constants:CURSOR_SHOW",
    "CURSOR_BLOCK": "ornata.definitions.constants:CURSOR_BLOCK",
    "CURSOR_UNDERLINE": "ornata.definitions.constants:CURSOR_UNDERLINE",
    "CURSOR_BAR": "ornata.definitions.constants:CURSOR_BAR",
    "CLEAR_SCREEN": "ornata.definitions.constants:CLEAR_SCREEN",
    "CLEAR_SCREEN_FROM_CURSOR": "ornata.definitions.constants:CLEAR_SCREEN_FROM_CURSOR",
    "CLEAR_SCREEN_TO_CURSOR": "ornata.definitions.constants:CLEAR_SCREEN_TO_CURSOR",
    "CLEAR_LINE": "ornata.definitions.constants:CLEAR_LINE",
    "CLEAR_LINE_FROM_CURSOR": "ornata.definitions.constants:CLEAR_LINE_FROM_CURSOR",
    "CLEAR_LINE_TO_CURSOR": "ornata.definitions.constants:CLEAR_LINE_TO_CURSOR",
    "ENTER_ALTERNATE_BUFFER": "ornata.definitions.constants:ENTER_ALTERNATE_BUFFER",
    "EXIT_ALTERNATE_BUFFER": "ornata.definitions.constants:EXIT_ALTERNATE_BUFFER",
    "SCROLL_UP": "ornata.definitions.constants:SCROLL_UP",
    "SCROLL_DOWN": "ornata.definitions.constants:SCROLL_DOWN",
    "ERASE_DISPLAY": "ornata.definitions.constants:ERASE_DISPLAY",
    "ERASE_LINE": "ornata.definitions.constants:ERASE_LINE",
    "WINDOW_CLASS_NAME": "ornata.definitions.constants:WINDOW_CLASS_NAME",
    "WS_OVERLAPPEDWINDOW": "ornata.definitions.constants:WS_OVERLAPPEDWINDOW",
    "WS_VISIBLE": "ornata.definitions.constants:WS_VISIBLE",
    "CW_USEDEFAULT": "ornata.definitions.constants:CW_USEDEFAULT",
    "WM_DESTROY": "ornata.definitions.constants:WM_DESTROY",
    "WM_PAINT": "ornata.definitions.constants:WM_PAINT",
    "WM_SIZE": "ornata.definitions.constants:WM_SIZE",
    "WM_CLOSE": "ornata.definitions.constants:WM_CLOSE",
    "WM_KEYDOWN": "ornata.definitions.constants:WM_KEYDOWN",
    "WM_KEYUP": "ornata.definitions.constants:WM_KEYUP",
    "WM_LBUTTONDOWN": "ornata.definitions.constants:WM_LBUTTONDOWN",
    "WM_LBUTTONUP": "ornata.definitions.constants:WM_LBUTTONUP",
    "WM_RBUTTONDOWN": "ornata.definitions.constants:WM_RBUTTONDOWN",
    "WM_RBUTTONUP": "ornata.definitions.constants:WM_RBUTTONUP",
    "WM_MOUSEMOVE": "ornata.definitions.constants:WM_MOUSEMOVE",
    "WM_MOUSEWHEEL": "ornata.definitions.constants:WM_MOUSEWHEEL",
    "VK_ESCAPE": "ornata.definitions.constants:VK_ESCAPE",
    "VK_SHIFT": "ornata.definitions.constants:VK_SHIFT",
    "VK_CONTROL": "ornata.definitions.constants:VK_CONTROL",
    "VK_MENU": "ornata.definitions.constants:VK_MENU",
    "HWND_MESSAGE": "ornata.definitions.constants:HWND_MESSAGE",
    "AnimationEventType": "ornata.definitions.enums:AnimationEventType",
    "AnimationDirection": "ornata.definitions.enums:AnimationDirection",
    "BufferUsage": "ornata.definitions.enums:BufferUsage",
    "RendererType": "ornata.definitions.enums:RendererType",
    "BlendMode": "ornata.definitions.enums:BlendMode",
    "BlendFactor": "ornata.definitions.enums:BlendFactor",
    "BlendOperation": "ornata.definitions.enums:BlendOperation",
    "DepthFunction": "ornata.definitions.enums:DepthFunction",
    "CullMode": "ornata.definitions.enums:CullMode",
    "FillMode": "ornata.definitions.enums:FillMode",
    "ResidencyState": "ornata.definitions.enums:ResidencyState",
    "TransferDirection": "ornata.definitions.enums:TransferDirection",
    "BarrierType": "ornata.definitions.enums:BarrierType",
    "SyncType": "ornata.definitions.enums:SyncType",
    "FilterMode": "ornata.definitions.enums:FilterMode",
    "WrapMode": "ornata.definitions.enums:WrapMode",
    "CubeMapFace": "ornata.definitions.enums:CubeMapFace",
    "TextureFormat": "ornata.definitions.enums:TextureFormat",
    "TextureUsage": "ornata.definitions.enums:TextureUsage",
    "InputEventType": "ornata.definitions.enums:InputEventType",
    "InputState": "ornata.definitions.enums:InputState",
    "KeyEventType": "ornata.definitions.enums:KeyEventType",
    "MouseEventType": "ornata.definitions.enums:MouseEventType",
    "FrameState": "ornata.definitions.enums:FrameState",
    "PipelineStage": "ornata.definitions.enums:PipelineStage",
    "SignalType": "ornata.definitions.enums:SignalType",
    "PatchType": "ornata.definitions.enums:PatchType",
    "BackendTarget": "ornata.definitions.enums:BackendTarget",
    "TerminalCapability": "ornata.definitions.enums:TerminalCapability",
    "TerminalType": "ornata.definitions.enums:TerminalType",
    "TerminalMode": "ornata.definitions.enums:TerminalMode",
    "SGRCode": "ornata.definitions.enums:SGRCode",
    "Color8": "ornata.definitions.enums:Color8",
    "EraseMode": "ornata.definitions.enums:EraseMode",
    "EventPriority": "ornata.definitions.enums:EventPriority",
    "EventType": "ornata.definitions.enums:EventType",
    "ComponentKind": "ornata.definitions.enums:ComponentKind",
    "InteractionType": "ornata.definitions.enums:InteractionType",
    "Alignment": "ornata.definitions.enums:Alignment",
    "AssetType": "ornata.definitions.enums:AssetType",
    "LogLevel": "ornata.definitions.enums:LogLevel",
    "ShaderStage": "ornata.definitions.enums:ShaderStage",
    "CompilationStatus": "ornata.definitions.enums:CompilationStatus",
    "ShaderBackendType": "ornata.definitions.enums:ShaderBackendType",
    "BaseError": "ornata.definitions.errors:BaseError",
    "KernelError": "ornata.definitions.errors:KernelError",
    "ComponentError": "ornata.definitions.errors:ComponentError",
    "EffectsError": "ornata.definitions.errors:EffectsError",
    "EventError": "ornata.definitions.errors:EventError",
    "GPUError": "ornata.definitions.errors:GPUError",
    "LayoutError": "ornata.definitions.errors:LayoutError",
    "PluginError": "ornata.definitions.errors:PluginError",
    "RenderingError": "ornata.definitions.errors:RenderingError",
    "StylingError": "ornata.definitions.errors:StylingError",
    "VDOMError": "ornata.definitions.errors:VDOMError",
    "GUIError": "ornata.definitions.errors:GUIError",
    "KernelInitError": "ornata.definitions.errors:KernelInitError",
    "ConfigurationError": "ornata.definitions.errors:ConfigurationError",
    "BackendSelectionError": "ornata.definitions.errors:BackendSelectionError",
    "PluginLoadError": "ornata.definitions.errors:PluginLoadError",
    "SubsystemRegistrationError": "ornata.definitions.errors:SubsystemRegistrationError",
    "VersionCompatibilityError": "ornata.definitions.errors:VersionCompatibilityError",
    "ThemeLoadError": "ornata.definitions.errors:ThemeLoadError",
    "EventSystemInitError": "ornata.definitions.errors:EventSystemInitError",
    "CythonCompilationError": "ornata.definitions.errors:CythonCompilationError",
    "ComponentLifecycleError": "ornata.definitions.errors:ComponentLifecycleError",
    "ComponentMountError": "ornata.definitions.errors:ComponentMountError",
    "ComponentUnmountError": "ornata.definitions.errors:ComponentUnmountError",
    "ComponentUpdateError": "ornata.definitions.errors:ComponentUpdateError",
    "InvalidComponentStateError": "ornata.definitions.errors:InvalidComponentStateError",
    "InvalidPropError": "ornata.definitions.errors:InvalidPropError",
    "AnimationError": "ornata.definitions.errors:AnimationError",
    "InvalidKeyframeError": "ornata.definitions.errors:InvalidKeyframeError",
    "AnimationNotFoundError": "ornata.definitions.errors:AnimationNotFoundError",
    "AnimationStateError": "ornata.definitions.errors:AnimationStateError",
    "EasingFunctionError": "ornata.definitions.errors:EasingFunctionError",
    "ParticleError": "ornata.definitions.errors:ParticleError",
    "InvalidParticleConfigError": "ornata.definitions.errors:InvalidParticleConfigError",
    "ParticleSystemNotFoundError": "ornata.definitions.errors:ParticleSystemNotFoundError",
    "GPUBackendNotAvailableError": "ornata.definitions.errors:GPUBackendNotAvailableError",
    "GPUShaderCompilationError": "ornata.definitions.errors:GPUShaderCompilationError",
    "GPUDeviceError": "ornata.definitions.errors:GPUDeviceError",
    "GPUMemoryError": "ornata.definitions.errors:GPUMemoryError",
    "GPUPipelineError": "ornata.definitions.errors:GPUPipelineError",
    "GPUContextLostError": "ornata.definitions.errors:GPUContextLostError",
    "GPUFeatureUnsupportedError": "ornata.definitions.errors:GPUFeatureUnsupportedError",
    "GPUBufferError": "ornata.definitions.errors:GPUBufferError",
    "GPUBufferCreationError": "ornata.definitions.errors:GPUBufferCreationError",
    "GPUBufferUpdateError": "ornata.definitions.errors:GPUBufferUpdateError",
    "GPUBufferBindingError": "ornata.definitions.errors:GPUBufferBindingError",
    "GPUBufferAlignmentError": "ornata.definitions.errors:GPUBufferAlignmentError",
    "UnsupportedRendererError": "ornata.definitions.errors:UnsupportedRendererError",
    "CompositionError": "ornata.definitions.errors:CompositionError",
    "PipelineError": "ornata.definitions.errors:PipelineError",
    "FrameSubmissionError": "ornata.definitions.errors:FrameSubmissionError",
    "ValidationError": "ornata.definitions.errors:ValidationError",
    "StyleResolutionError": "ornata.definitions.errors:StyleResolutionError",
    "InvalidStyleValueError": "ornata.definitions.errors:InvalidStyleValueError",
    "StyleNotFoundError": "ornata.definitions.errors:StyleNotFoundError",
    "ThemeOverrideError": "ornata.definitions.errors:ThemeOverrideError",
    "ThemeTokenNotFoundError": "ornata.definitions.errors:ThemeTokenNotFoundError",
    "ComponentNotFoundError": "ornata.definitions.errors:ComponentNotFoundError",
    "InvalidVDOMOperationError": "ornata.definitions.errors:InvalidVDOMOperationError",
    "VDOMReconciliationError": "ornata.definitions.errors:VDOMReconciliationError",
    "DiffingError": "ornata.definitions.errors:DiffingError",
    "InvalidTreeStructureError": "ornata.definitions.errors:InvalidTreeStructureError",
    "PatchApplicationError": "ornata.definitions.errors:PatchApplicationError",
    "MissingKeyError": "ornata.definitions.errors:MissingKeyError",
    "KeyCollisionError": "ornata.definitions.errors:KeyCollisionError",
    "LayoutCalculationError": "ornata.definitions.errors:LayoutCalculationError",
    "InvalidLayoutConstraintsError": "ornata.definitions.errors:InvalidLayoutConstraintsError",
    "LayoutOverflowError": "ornata.definitions.errors:LayoutOverflowError",
    "LayoutUnderflowError": "ornata.definitions.errors:LayoutUnderflowError",
    "WindowCreationError": "ornata.definitions.errors:WindowCreationError",
    "ContextCreationError": "ornata.definitions.errors:ContextCreationError",
    "SurfaceCreationError": "ornata.definitions.errors:SurfaceCreationError",
    "GUIEventLoopError": "ornata.definitions.errors:GUIEventLoopError",
    "EventPropagationError": "ornata.definitions.errors:EventPropagationError",
    "InvalidEventTypeError": "ornata.definitions.errors:InvalidEventTypeError",
    "EventHandlerError": "ornata.definitions.errors:EventHandlerError",
    "EventReplayError": "ornata.definitions.errors:EventReplayError",
    "EventSubscriptionError": "ornata.definitions.errors:EventSubscriptionError",
    "EventQueueOverflowError": "ornata.definitions.errors:EventQueueOverflowError",
    "RenderCapability": "ornata.definitions.flags:RenderCapability",
    "PlatformEventHandler": "ornata.definitions.protocols:PlatformEventHandler",
    "RenderCallback": "ornata.definitions.protocols:RenderCallback",
    "Canvas": "ornata.definitions.protocols:Canvas",
    "GuiNodeLike": "ornata.definitions.protocols:GuiNodeLike",
    "WindowManagerProtocol": "ornata.definitions.protocols:WindowManagerProtocol",
    "MeasureProtocol": "ornata.definitions.protocols:MeasureProtocol",
    "LayoutAlgorithm": "ornata.definitions.protocols:LayoutAlgorithm",
    "LayoutConstraint": "ornata.definitions.protocols:LayoutConstraint",
    "ResponsiveBreakpoint": "ornata.definitions.protocols:ResponsiveBreakpoint",
    "LayoutCacheKey": "ornata.definitions.protocols:LayoutCacheKey",
    "LayoutStyleProtocol": "ornata.definitions.protocols:LayoutStyleProtocol",
    "ResolvedStyleProtocol": "ornata.definitions.protocols:ResolvedStyleProtocol",
    "BootstrapPhase": "ornata.definitions.protocols:BootstrapPhase",
    "ConfigLoader": "ornata.definitions.protocols:ConfigLoader",
    "BackendSelector": "ornata.definitions.protocols:BackendSelector",
    "PluginLoader": "ornata.definitions.protocols:PluginLoader",
    "SubsystemRegistry": "ornata.definitions.protocols:SubsystemRegistry",
    "HostObjectProtocol": "ornata.definitions.protocols:HostObjectProtocol",
    "ComponentFactory": "ornata.definitions.protocols:ComponentFactory",
    "Vector2": "ornata.definitions.type_alias:Vector2",
    "Vector3": "ornata.definitions.type_alias:Vector3",
    "Vector4": "ornata.definitions.type_alias:Vector4",
    "ErrorList": "ornata.definitions.type_alias:ErrorList",
    "WarningList": "ornata.definitions.type_alias:WarningList",
    "CacheLimit": "ornata.definitions.type_alias:CacheLimit",
    "BorderStyleType": "ornata.definitions.type_alias:BorderStyleType",
    "ANSI4BitRGBMap": "ornata.definitions.type_alias:ANSI4BitRGBMap",
    "AnsiColorCache": "ornata.definitions.type_alias:AnsiColorCache",
    "ANSISequenceList": "ornata.definitions.type_alias:ANSISequenceList",
    "BackgroundColorMap": "ornata.definitions.type_alias:BackgroundColorMap",
    "BoxGlyphMap": "ornata.definitions.type_alias:BoxGlyphMap",
    "ColorTransformMap": "ornata.definitions.type_alias:ColorTransformMap",
    "DrawRegistryMap": "ornata.definitions.type_alias:DrawRegistryMap",
    "EffectCodeMap": "ornata.definitions.type_alias:EffectCodeMap",
    "LoggingColorMap": "ornata.definitions.type_alias:LoggingColorMap",
    "NamedColorMap": "ornata.definitions.type_alias:NamedColorMap",
    "NamedHexMap": "ornata.definitions.type_alias:NamedHexMap",
    "RegexPattern": "ornata.definitions.type_alias:RegexPattern",
    "RouteMask": "ornata.definitions.type_alias:RouteMask",
    "SpacingScaleMap": "ornata.definitions.type_alias:SpacingScaleMap",
    "StylePropertySet": "ornata.definitions.type_alias:StylePropertySet",
    "SuffixToUnitMap": "ornata.definitions.type_alias:SuffixToUnitMap",
    "TypographyScaleMap": "ornata.definitions.type_alias:TypographyScaleMap",
    "ValuePatternMap": "ornata.definitions.type_alias:ValuePatternMap",
    "VirtualKeyCode": "ornata.definitions.type_alias:VirtualKeyCode",
    "WindowMessageCode": "ornata.definitions.type_alias:WindowMessageCode",
    "WindowStyleFlag": "ornata.definitions.type_alias:WindowStyleFlag",
    "components": "ornata.definitions.dataclasses:components",
    "core": "ornata.definitions.dataclasses:core",
    "effects": "ornata.definitions.dataclasses:effects",
    "events": "ornata.definitions.dataclasses:events",
    "gpu": "ornata.definitions.dataclasses:gpu",
    "kernel": "ornata.definitions.dataclasses:kernel",
    "layout": "ornata.definitions.dataclasses:layout",
    "plugins": "ornata.definitions.dataclasses:plugins",
    "rendering": "ornata.definitions.dataclasses:rendering",
    "shared": "ornata.definitions.dataclasses:shared",
    "styling": "ornata.definitions.dataclasses:styling",
    "vdom": "ornata.definitions.dataclasses:vdom",
    "StateBlock": "ornata.definitions.dataclasses.components:StateBlock",
    "ComponentRule": "ornata.definitions.dataclasses.components:ComponentRule",
    "ComponentPlacement": "ornata.definitions.dataclasses.components:ComponentPlacement",
    "ComponentContent": "ornata.definitions.dataclasses.components:ComponentContent",
    "ComponentDataBinding": "ornata.definitions.dataclasses.components:ComponentDataBinding",
    "ComponentAccessibility": "ornata.definitions.dataclasses.components:ComponentAccessibility",
    "InteractionDescriptor": "ornata.definitions.dataclasses.components:InteractionDescriptor",
    "ComponentRenderHints": "ornata.definitions.dataclasses.components:ComponentRenderHints",
    "ComponentMeasurement": "ornata.definitions.dataclasses.components:ComponentMeasurement",
    "ComponentVersion": "ornata.definitions.dataclasses.components:ComponentVersion",
    "VersionConstraint": "ornata.definitions.dataclasses.components:VersionConstraint",
    "ComponentInfo": "ornata.definitions.dataclasses.components:ComponentInfo",
    "Component": "ornata.definitions.dataclasses.components:Component",
    "AppConfig": "ornata.definitions.dataclasses.core:AppConfig",
    "RuntimeFrame": "ornata.definitions.dataclasses.core:RuntimeFrame",
    "BaseHostObject": "ornata.definitions.dataclasses.core:BaseHostObject",
    "AssetInfo": "ornata.definitions.dataclasses.core:AssetInfo",
    "AnimationState": "ornata.definitions.dataclasses.effects:AnimationState",
    "ScheduledCallback": "ornata.definitions.dataclasses.effects:ScheduledCallback",
    "Particle": "ornata.definitions.dataclasses.effects:Particle",
    "Keyframe": "ornata.definitions.dataclasses.effects:Keyframe",
    "Keyframes": "ornata.definitions.dataclasses.effects:Keyframes",
    "Animation": "ornata.definitions.dataclasses.effects:Animation",
    "QueuedEffect": "ornata.definitions.dataclasses.effects:QueuedEffect",
    "QueuedAsyncEffect": "ornata.definitions.dataclasses.effects:QueuedAsyncEffect",
    "AnimationEvent": "ornata.definitions.dataclasses.effects:AnimationEvent",
    "Transform": "ornata.definitions.dataclasses.effects:Transform",
    "EventPoolConfig": "ornata.definitions.dataclasses.events:EventPoolConfig",
    "EventPoolStats": "ornata.definitions.dataclasses.events:EventPoolStats",
    "EventHandlerWrapper": "ornata.definitions.dataclasses.events:EventHandlerWrapper",
    "EventFilterWrapper": "ornata.definitions.dataclasses.events:EventFilterWrapper",
    "KeyEvent": "ornata.definitions.dataclasses.events:KeyEvent",
    "MouseEvent": "ornata.definitions.dataclasses.events:MouseEvent",
    "Event": "ornata.definitions.dataclasses.events:Event",
    "QuitEvent": "ornata.definitions.dataclasses.events:QuitEvent",
    "TickEvent": "ornata.definitions.dataclasses.events:TickEvent",
    "BatchedEvent": "ornata.definitions.dataclasses.events:BatchedEvent",
    "ComponentEvent": "ornata.definitions.dataclasses.events:ComponentEvent",
    "GPUBufferHandle": "ornata.definitions.dataclasses.gpu:GPUBufferHandle",
    "GPUTextureHandle": "ornata.definitions.dataclasses.gpu:GPUTextureHandle",
    "VertexAttribute": "ornata.definitions.dataclasses.gpu:VertexAttribute",
    "CompilationResult": "ornata.definitions.dataclasses.gpu:CompilationResult",
    "ShaderMacro": "ornata.definitions.dataclasses.gpu:ShaderMacro",
    "CompiledShader": "ornata.definitions.dataclasses.gpu:CompiledShader",
    "BatchKey": "ornata.definitions.dataclasses.gpu:BatchKey",
    "BatchedGeometry": "ornata.definitions.dataclasses.gpu:BatchedGeometry",
    "PersistentBuffer": "ornata.definitions.dataclasses.gpu:PersistentBuffer",
    "MemoryAlignment": "ornata.definitions.dataclasses.gpu:MemoryAlignment",
    "InstanceTransform":"ornata.definitions.dataclasses.gpu:InstanceTransform",
    "Matrix4":"ornata.definitions.dataclasses.gpu:Matrix4",
    "BlendState":"ornata.definitions.dataclasses.gpu:BlendState",
    "DepthState":"ornata.definitions.dataclasses.gpu:DepthState",
    "RasterizerState":"ornata.definitions.dataclasses.gpu:RasterizerState",
    "PipelineConfig":"ornata.definitions.dataclasses.gpu:PipelineConfig",
    "ComponentIdentity":"ornata.definitions.dataclasses.gpu:ComponentIdentity",
    "InstanceGroup":"ornata.definitions.dataclasses.gpu:InstanceGroup",
    "InstancedShader":"ornata.definitions.dataclasses.gpu:InstancedShader",
    "MemoryBlock":"ornata.definitions.dataclasses.gpu:MemoryBlock",
    "BufferStats":"ornata.definitions.dataclasses.gpu:BufferStats",
    "TransferRequest":"ornata.definitions.dataclasses.gpu:TransferRequest",
    "SyncPoint":"ornata.definitions.dataclasses.gpu:SyncPoint",
    "GPUTextureInfo":"ornata.definitions.dataclasses.gpu:GPUTextureInfo",
    "BindingGroup":"ornata.definitions.dataclasses.gpu:BindingGroup",
    "GPUBackendInfo":"ornata.definitions.dataclasses.gpu:GPUBackendInfo",
    "GPUBufferInfo":"ornata.definitions.dataclasses.gpu:GPUBufferInfo",
    "Geometry":"ornata.definitions.dataclasses.gpu:Geometry",
    "CompositorLayer":"ornata.definitions.dataclasses.gpu:CompositorLayer",
    "ShaderUniform":"ornata.definitions.dataclasses.gpu:ShaderUniform",
    "ShaderAttribute":"ornata.definitions.dataclasses.gpu:ShaderAttribute",
    "PipelineDefinition":"ornata.definitions.dataclasses.gpu:PipelineDefinition",
    "KernelConfig":"ornata.definitions.dataclasses.kernel:KernelConfig",
    "KernelState":"ornata.definitions.dataclasses.kernel:KernelState",
    "SubsystemInfo":"ornata.definitions.dataclasses.kernel:SubsystemInfo",
    "SpatialIndexEntry":"ornata.definitions.dataclasses.layout:SpatialIndexEntry",
    "LayoutDebugInfo":"ornata.definitions.dataclasses.layout:LayoutDebugInfo",
    "LayoutResult":"ornata.definitions.dataclasses.layout:LayoutResult",
    "LayoutStyle":"ornata.definitions.dataclasses.layout:LayoutStyle",
    "Bounds":"ornata.definitions.dataclasses.layout:Bounds",
    "LayoutConstraints":"ornata.definitions.dataclasses.layout:LayoutConstraints",
    "LayoutInput":"ornata.definitions.dataclasses.layout:LayoutInput",
    "VirtualScrollConfig":"ornata.definitions.dataclasses.layout:VirtualScrollConfig",
    "VirtualScrollState":"ornata.definitions.dataclasses.layout:VirtualScrollState",
    "UnicodeCanvas":"ornata.definitions.dataclasses.rendering:UnicodeCanvas",
    "InputModifierState":"ornata.definitions.dataclasses.rendering:InputModifierState",
    "GuiInputEvent":"ornata.definitions.dataclasses.rendering:GuiInputEvent",
    "InputContext":"ornata.definitions.dataclasses.rendering:InputContext",
    "Win32WindowManager":"ornata.definitions.dataclasses.rendering:Win32WindowManager",
    "WindowPumpHandle":"ornata.definitions.dataclasses.rendering:WindowPumpHandle",
    "TerminalState":"ornata.definitions.dataclasses.rendering:TerminalState",
    "RenderOutput":"ornata.definitions.dataclasses.rendering:RenderOutput",
    "RendererCapabilities":"ornata.definitions.dataclasses.rendering:RendererCapabilities",
    "LayerTransform":"ornata.definitions.dataclasses.rendering:LayerTransform",
    "Layer":"ornata.definitions.dataclasses.rendering:Layer",
    "FrameTiming":"ornata.definitions.dataclasses.rendering:FrameTiming",
    "Frame":"ornata.definitions.dataclasses.rendering:Frame",
    "FrameStats":"ornata.definitions.dataclasses.rendering:FrameStats",
    "PipelineMetrics":"ornata.definitions.dataclasses.rendering:PipelineMetrics",
    "RenderSignal":"ornata.definitions.dataclasses.rendering:RenderSignal",
    "SurfaceMetadata":"ornata.definitions.dataclasses.rendering:SurfaceMetadata",
    "Surface":"ornata.definitions.dataclasses.rendering:Surface",
    "TextSurface":"ornata.definitions.dataclasses.rendering:TextSurface",
    "PixelSurface":"ornata.definitions.dataclasses.rendering:PixelSurface",
    "RenderOptions":"ornata.definitions.dataclasses.rendering:RenderOptions",
    "TerminalInfo":"ornata.definitions.dataclasses.rendering:TerminalInfo",
    "CursorPosition":"ornata.definitions.dataclasses.rendering:CursorPosition",
    "ScreenRegion":"ornata.definitions.dataclasses.rendering:ScreenRegion",
    "ScreenCell":"ornata.definitions.dataclasses.rendering:ScreenCell",
    "ScreenBuffer":"ornata.definitions.dataclasses.rendering:ScreenBuffer",
    "GuiNode":"ornata.definitions.dataclasses.rendering:GuiNode",
    "BackendCapabilities":"ornata.definitions.dataclasses.rendering:BackendCapabilities",
    "DirtyRegion":"ornata.definitions.dataclasses.rendering:DirtyRegion",
    "RenderBatch":"ornata.definitions.dataclasses.rendering:RenderBatch",
    "Rect":"ornata.definitions.dataclasses.rendering:Rect",
    "VDOMRendererContext":"ornata.definitions.dataclasses.shared:VDOMRendererContext",
    "AdapterContext":"ornata.definitions.dataclasses.shared:AdapterContext",
    "DefaultHostObject":"ornata.definitions.dataclasses.shared:DefaultHostObject",
    "StandardHostObject":"ornata.definitions.dataclasses.shared:StandardHostObject",
    "PaletteEntry":"ornata.definitions.dataclasses.styling:PaletteEntry",
    "Span":"ornata.definitions.dataclasses.styling:Span",
    "ColorToken":"ornata.definitions.dataclasses.styling:ColorToken",
    "FontDef":"ornata.definitions.dataclasses.styling:FontDef",
    "Property":"ornata.definitions.dataclasses.styling:Property",
    "Stylesheet":"ornata.definitions.dataclasses.styling:Stylesheet",
    "ResolvedStyle":"ornata.definitions.dataclasses.styling:ResolvedStyle",
    "Border":"ornata.definitions.dataclasses.styling:Border",
    "FontProfile":"ornata.definitions.dataclasses.styling:FontProfile",
    "RGBA":"ornata.definitions.dataclasses.styling:RGBA",
    "HSLA":"ornata.definitions.dataclasses.styling:HSLA",
    "ColorFunction":"ornata.definitions.dataclasses.styling:ColorFunction",
    "ColorBlend":"ornata.definitions.dataclasses.styling:ColorBlend",
    "BoxShadow":"ornata.definitions.dataclasses.styling:BoxShadow",
    "BorderRadius":"ornata.definitions.dataclasses.styling:BorderRadius",
    "TextShadow":"ornata.definitions.dataclasses.styling:TextShadow",
    "Gradient":"ornata.definitions.dataclasses.styling:Gradient",
    "StylingContext":"ornata.definitions.dataclasses.styling:StylingContext",
    "Color":"ornata.definitions.dataclasses.styling:Color",
    "Font":"ornata.definitions.dataclasses.styling:Font",
    "TypographyStyle":"ornata.definitions.dataclasses.styling:TypographyStyle",
    "BorderStyle":"ornata.definitions.dataclasses.styling:BorderStyle",
    "ShadowStyle":"ornata.definitions.dataclasses.styling:ShadowStyle",
    "Theme":"ornata.definitions.dataclasses.styling:Theme",
    "ThemePalette":"ornata.definitions.dataclasses.styling:ThemePalette",
    "ANSIColor":"ornata.definitions.dataclasses.styling:ANSIColor",
    "TextStyle":"ornata.definitions.dataclasses.styling:TextStyle",
    "CacheKey":"ornata.definitions.dataclasses.styling:CacheKey",
    "Lexer":"ornata.definitions.dataclasses.styling:Lexer",
    "Length":"ornata.definitions.dataclasses.styling:Length",
    "Insets":"ornata.definitions.dataclasses.styling:Insets",
    "Transition":"ornata.definitions.dataclasses.styling:Transition",
    "MediaQuery":"ornata.definitions.dataclasses.styling:MediaQuery",
    "MediaRule":"ornata.definitions.dataclasses.styling:MediaRule",
    "PropertyMeta":"ornata.definitions.dataclasses.styling:PropertyMeta",
    "Patch":"ornata.definitions.dataclasses.vdom:Patch",
    "VDOMNode":"ornata.definitions.dataclasses.vdom:VDOMNode",
    "VDOMTree":"ornata.definitions.dataclasses.vdom:VDOMTree",
    "PatchPoolConfig":"ornata.definitions.dataclasses.vdom:PatchPoolConfig",
    "PatchPoolStats":"ornata.definitions.dataclasses.vdom:PatchPoolStats",
    "PluginMetadata":"ornata.definitions.dataclasses.plugins:PluginMetadata",
    "LengthUnit":"ornata.definitions.type_alias:LengthUnit",
    "ColorSpec":"ornata.definitions.type_alias:ColorSpec",
    "EasingFunction":"ornata.definitions.type_alias:EasingFunction",
    "FlexDirection":"ornata.definitions.type_alias:FlexDirection",
    "JustifyContent":"ornata.definitions.type_alias:JustifyContent",
    "AlignItems":"ornata.definitions.type_alias:AlignItems",
    "TextDecorationStyle":"ornata.definitions.type_alias:TextDecorationStyle",
    "TextTransform":"ornata.definitions.type_alias:TextTransform",
    "TextAlign":"ornata.definitions.type_alias:TextAlign",
    "VerticalAlign":"ornata.definitions.type_alias:VerticalAlign",
    "SignalHandler":"ornata.definitions.type_alias:SignalHandler",
    "DrawFunc":"ornata.definitions.type_alias:DrawFunc",
}

_RESOLVED_EXPORTS: dict[str, object] = {}

__all__ = ["__getattr__"]

def _load_target(name: str) -> object:
    """Load and cache ``name`` for this subsystem.

    Parameters
    ----------
    name : str
        Export name to resolve.

    Returns
    -------
    object
        Resolved attribute from the owning module.

    Raises
    ------
    AttributeError
        If ``name`` is unknown to this subsystem.
    """

    target = _EXPORT_TARGETS.get(name)
    if target is None:
        raise AttributeError(
            "module 'ornata.api.exports.components' has no attribute {name!r}"
        )
    module_name, _, attr_name = target.partition(':')
    module = import_module(module_name)
    value = getattr(module, attr_name)
    _RESOLVED_EXPORTS[name] = value
    globals()[name] = value
    return value

def __getattr__(name: str) -> object:
    """Resolve an export attribute on first access.

    Parameters
    ----------
    name : str
        Export name requested from this module.

    Returns
    -------
    object
        Resolved export value.

    Raises
    ------
    AttributeError
        If ``name`` is not part of this subsystem.
    """

    if name in _RESOLVED_EXPORTS:
        return _RESOLVED_EXPORTS[name]
    return _load_target(name)

def __dir__() -> list[str]:
    """Return the sorted list of exportable names.

    Returns
    -------
    list[str]
        Sorted names available via this module.
    """

    names = ['__getattr__']
    names.extend(_EXPORT_TARGETS)
    return sorted(names)
