"""Auto-generated exports for ornata.effects.animation."""

from __future__ import annotations

from . import coordinator, easing, effects, engine, events, interfaces, keyframes, optimization, timeline
from .coordinator import (
    AnimationCoordinator,
    AnimationSequence,
)
from .easing import (
    ease_in_back,
    ease_in_bounce,
    ease_in_circ,
    ease_in_cubic,
    ease_in_elastic,
    ease_in_expo,
    ease_in_out_back,
    ease_in_out_bounce,
    ease_in_out_circ,
    ease_in_out_cubic,
    ease_in_out_elastic,
    ease_in_out_expo,
    ease_in_out_quad,
    ease_in_out_quart,
    ease_in_out_sine,
    ease_in_quad,
    ease_in_quart,
    ease_in_sine,
    ease_out_back,
    ease_out_bounce,
    ease_out_circ,
    ease_out_cubic,
    ease_out_elastic,
    ease_out_expo,
    ease_out_quad,
    ease_out_quart,
    ease_out_sine,
    linear_easing,
)
from .effects import (
    FadeInAnimation,
    GradientPulseAnimation,
    ParticleTrailAnimation,
    PulseAnimation,
    ShakeAnimation,
    TypewriterAnimation,
    WaveAnimation,
)
from .engine import AnimationEngine
from .events import (
    AnimationEventDispatcher,
    dispatch_animation_event,
    get_event_dispatcher,
)
from .interfaces import (
    _get_animation_engine,  # type: ignore [private]
    animate_component,
    create_timeline,
    get_active_animations,
    get_timeline,
    pause_animation,
    resume_animation,
    start_animation,
    stop_animation,
    update_animations,
)
from .keyframes import Animation
from .optimization import AnimationBatcher, AnimationOptimizer
from .timeline import AnimationScheduler, Timeline

__all__ = [
    "Animation",
    "AnimationBatcher",
    "AnimationCoordinator",
    "AnimationEngine",
    "AnimationEventDispatcher",
    "AnimationOptimizer",
    "AnimationScheduler",
    "AnimationSequence",
    "FadeInAnimation",
    "GradientPulseAnimation",
    "ParticleTrailAnimation",
    "PulseAnimation",
    "ShakeAnimation",
    "Timeline",
    "TypewriterAnimation",
    "WaveAnimation",
    "_get_animation_engine",
    "animate_component",
    "coordinator",
    "create_timeline",
    "dispatch_animation_event",
    "ease_in_back",
    "ease_in_bounce",
    "ease_in_circ",
    "ease_in_cubic",
    "ease_in_elastic",
    "ease_in_expo",
    "ease_in_out_back",
    "ease_in_out_bounce",
    "ease_in_out_circ",
    "ease_in_out_cubic",
    "ease_in_out_elastic",
    "ease_in_out_expo",
    "ease_in_out_quad",
    "ease_in_out_quart",
    "ease_in_out_sine",
    "ease_in_quad",
    "ease_in_quart",
    "ease_in_sine",
    "ease_out_back",
    "ease_out_bounce",
    "ease_out_circ",
    "ease_out_cubic",
    "ease_out_elastic",
    "ease_out_expo",
    "ease_out_quad",
    "ease_out_quart",
    "ease_out_sine",
    "easing",
    "effects",
    "engine",
    "events",
    "get_active_animations",
    "get_event_dispatcher",
    "get_timeline",
    "interfaces",
    "keyframes",
    "linear_easing",
    "optimization",
    "pause_animation",
    "resume_animation",
    "start_animation",
    "stop_animation",
    "timeline",
    "update_animations",
]
